name: Documentation

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * *'  # Every day at 00:00 UTC

permissions:
  contents: read

jobs:
  doc:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Mesa (software OpenGL)
        run: sudo apt-get install -y libgl1 mesa-utils xvfb

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          use-mamba: false
          python-version: 3.11
          auto-activate-base: false
          miniforge-variant: Miniforge3

      - name: Create environment
        run: |
          conda create -n plaid-ops python=3.11 muscat=2.5.0 -c conda-forge
          conda run -n plaid-ops python -m pip install -e .[dev]


      - name: Compile documentation
        run: |
          cd docs
          conda run -n plaid-ops bash generate_doc.sh
