name: Lint, format and type check

permissions:
  contents: read

on:
  pull_request:
    branches: [main]

jobs:
  ruff:
    name: Ruff format && check and type check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install library
        run: |
          python -m pip install --upgrade pip
          pip install ruff pyright[nodejs]

      - name: lint
        run: ruff check .

      - name: format check
        run: ruff format --check .

      - name: Run pyright
        run: pyright